@startuml ProjectPlan

Class Agent {
    Matrix Chromosome
    StateHistory history
    AgentAction GetAgentAction(SystemState)
}

struct AgentAction {
    Vector ActionVector
}

interface System {
    int NumActions
    int NumPercepts
    float ScoreFunction(StateHistory)
    SystemState AdvanceState(SystemState, AgentActions[])
}

struct SystemState {
    Vector state
}

struct StateHistory {
    SystemState[] history
    void AddStateToHistory(SystemState)
}

class Manager {
    int GenerationIndex
    Agent[] Generation
    Agent[] BestAgentByGeneration
}

class Simulator {
    Agent[] Agents
    StateHistory History
}

class GeneticBreeder {
    float[] AgentScores
    Agent[] NextGeneration(Agent[])
}

class DataCollector {
    WriteData()
}

Agent -r-* Manager
System -l-* Manager
GeneticBreeder -u-* Manager
DataCollector -u-* Manager

Agent *-d- AgentAction

System *-u- StateHistory
StateHistory *-l- SystemState

Simulator -d- Manager: Concurrent Processing

@enduml